const app = require('./server');
const http = require('node:http');
const { db, insertEvent } = require('./db');
const { checkAndFinalizeDeadSessions } = require('./services/autoFinalizer');

const PORT = 3097;
const server = http.createServer(app);

server.listen(PORT, async () => {
    console.log(`\n======================================================`);
    console.log(`🧪 Testing Auto-Finalizer (Dead Man's Switch) on port ${PORT}`);
    console.log(`======================================================\n`);

    try {
        const baseUrl = `http://localhost:${PORT}`;

        // 1. Simulate a session where Chrome was abruptly closed 25 seconds ago
        const pastTime = new Date(Date.now() - 25000).toISOString();
        const testSessionId = 'sess-abrupt-test-' + Date.now();
        const testUrl = 'https://vnexpress.net/thoi-su/bai-bao-abrupt-close.html';

        console.log('--- 1. Seeding session with no PAGE_LEAVE (abrupt close 25s ago) ---');
        insertEvent({
            event_id: 'evt-abrupt-1',
            event_type: 'PAGE_ENTER',
            session_id: testSessionId,
            url: testUrl,
            domain: 'vnexpress.net',
            title: 'Bài báo đóng tab đột ngột',
            timestamp: new Date(Date.now() - 35000).toISOString(),
            payload: { active_reading_time_sec: 0, scroll_percent: 10 }
        });

        insertEvent({
            event_id: 'evt-abrupt-2',
            event_type: 'PAGE_ACTIVE',
            session_id: testSessionId,
            url: testUrl,
            domain: 'vnexpress.net',
            title: 'Bài báo đóng tab đột ngột',
            timestamp: pastTime, // Heartbeat sent 25s ago
            payload: { reason: 'heartbeat', active_reading_time_sec: 10, scroll_percent: 65 }
        });

        // 2. Trigger Auto-Finalizer check
        console.log('\n--- 2. Running checkAndFinalizeDeadSessions() ---');
        checkAndFinalizeDeadSessions();

        // 3. Verify that synthetic PAGE_LEAVE was generated in database
        console.log('\n--- 3. Verifying database events for this session ---');
        const sessionEvents = db.prepare(`SELECT * FROM events WHERE session_id = ? ORDER BY timestamp ASC`).all(testSessionId);
        console.log(`Total events for session: ${sessionEvents.length}`);
        sessionEvents.forEach(e => {
            console.log(`- ${e.event_type} at ${e.timestamp} | Payload: ${e.payload}`);
        });

        const lastEvt = sessionEvents[sessionEvents.length - 1];
        const isSyntheticLeave = lastEvt.event_type === 'PAGE_LEAVE' && ePayloadHasAutoFinalized(lastEvt.payload);

        if (isSyntheticLeave) {
            console.log('\n✅ PASS: Synthetic PAGE_LEAVE was successfully generated by Auto-Finalizer!');
        } else {
            console.error('\n❌ FAIL: Expected synthetic PAGE_LEAVE at the end of the session.');
        }

        // 4. Verify API detail endpoint
        console.log('\n--- 4. Verifying GET /api/articles/detail?url=... ---');
        const detailRes = await fetch(`${baseUrl}/api/articles/detail?url=${encodeURIComponent(testUrl)}`);
        const detailData = await detailRes.json();
        console.log('Article status:', detailData.data.status);
        console.log('Timeline length:', detailData.data.timeline.length);
        console.log('Last timeline event:', detailData.data.timeline[detailData.data.timeline.length - 1]);

        console.log('\n🎉 ALL AUTO-FINALIZER TESTS PASSED SUCCESSFULLY!\n');
    } catch (err) {
        console.error('Test error:', err);
    } finally {
        server.close(() => {
            console.log('Test server closed.');
            process.exit(0);
        });
    }
});

function ePayloadHasAutoFinalized(payloadStr) {
    try {
        const p = JSON.parse(payloadStr);
        return p.auto_finalized === true && p.exit_type === 'timeout_abrupt_exit';
    } catch {
        return false;
    }
}
